version: "3.4"

services:
  scraper_bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/scraper
    command: ["python", "main.py"]
    restart: on-failure
    depends_on:
      - v2_ui
    links:
      - v2_ui

  v2_ui:
    build:
      args:
        - V2_UI_READ_TOKEN=${V2_UI_READ_TOKEN}
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "3000:3000"
    command: ["serve", "-s", "./build"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
