apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-job
  labels:
    app: scraper-bot
spec:
  template:
    spec:
      containers:
        - name: local-ui
          image: UI_IMAGE_NAME
          command: ["/bin/bash", "-c", "touch /liveness-data/finished && serve -s ./build"]
          ports:
            - containerPort: 3000
              protocol: 'TCP'
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
          lifecycle:
            postStart:
              exec:
                command: ["sh", "wait_for_ui.sh"]
          livenessProbe:
            exec:
              command: ["cat", "/liveness-data/finished"]
            initialDelaySeconds: 60
            periodSeconds: 5
          volumeMounts:
          - name: liveness-data
            mountPath: /liveness-data
        - name: scraper-bot
          command: ["python", "main.py"]
          image: SCRAPER_IMAGE_NAME
          lifecycle:
            preStop:
              exec:
                command: ["rm", "-f", "/liveness-data/finished"]
          volumeMounts:
          - name: liveness-data
            mountPath: /liveness-data
      restartPolicy: Never
      volumes:
      - name: liveness-data
        emptyDir: {}
