apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
  labels:
    app: scraper-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-bot
  template:
    metadata:
      labels:
        app: scraper-bot
    spec:
      containers:
        - name: local-ui
          image: UI_IMAGE_NAME
          imagePullPolicy: Always
          command: ["sh", "run_ui.sh"]
          ports:
            - containerPort: 3000
              protocol: 'TCP'
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
          lifecycle:
            postStart:
              exec:
                command: ["sh", "wait_for_ui.sh"]
        - name: scraper-bot
          command: ["sh", "-c", "python main.py"]
          image: SCRAPER_IMAGE_NAME
          imagePullPolicy: Always
