apiVersion: v1
kind: Pod
metadata:
  name: scraper-bot
  labels:
    app: scraper-bot
spec:
  containers:
    - name: local-ui
      image: UI_IMAGE_NAME
      command: ["serve", "-s", "./build"]
      ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "4Gi"
          cpu: "500m"
      lifecycle:
        postStart:
          exec:
            command: ["sh", "wait_for_ui.sh"]
    - name: scraper-bot
      command: ["python", "main.py"]
      image: SCRAPER_IMAGE_NAME
  restartPolicy: OnFailure
  maxRetries: 3
status: {}
