apiVersion: v1
kind: Pod
metadata:
  name: scraper-bot
  labels:
    app: scraper-bot
spec:
  containers:
    - name: local-ui
      image: UI_IMAGE_NAME
      imagePullPolicy: Always
      command: ["sh", "-c", "serve -s ./build & read -t 600 ;  kill $!"]
      ports:
        - containerPort: 3000
          protocol: 'TCP'
      resources:
        requests:
          memory: "4Gi"
          cpu: "500m"
      lifecycle:
        postStart:
          exec:
            command: ["sh", "wait_for_ui.sh"]
    - name: scraper-bot
      command: ["sh", "-c", "python main.py"]
      image: SCRAPER_IMAGE_NAME
      imagePullPolicy: Always
  restartPolicy: OnFailure
